print('Swamiye Saranam Ayyappa')
print('Vinayagar Thunai')
print('Veerakumar Thunai')
print('Karivaratharaja Perumal Thunai')
print('Karana Perumal Thunai')
print('Thirupathi Perumal Thunai')
print('Kariya Kali Amman Thunai')